version: '3.1'

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/app
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
    tty: true
    networks:
      - shortener

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      - shortener

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DB_DOCKER_URL}
    networks:
      - shortener

volumes:
  mongodb:
  mongodb_config:
networks:
  shortener: